# Generated by Django 4.0 on 2021-12-24 13:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mathexp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('admissionYear', models.PositiveIntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), mathexp.models.Student.max_value_current_year])),
                ('schoolClassNum', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], default='класс не выбран', max_length=5)),
                ('schoolClassName', models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В')], default='класс не выбран', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MathExpressions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mathExpression', models.CharField(max_length=255)),
                ('validExpression', models.PositiveIntegerField(default=0, validators=[mathexp.models.MathExpressions.validate_even])),
                ('nonvalidExpression', models.PositiveIntegerField(default=0, validators=[mathexp.models.MathExpressions.validate_even])),
                ('validMathResolve', models.PositiveIntegerField(default=0, validators=[mathexp.models.MathExpressions.validate_even])),
                ('nonvalidMathResolve', models.PositiveIntegerField(default=0, validators=[mathexp.models.MathExpressions.validate_even])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathexp.student')),
            ],
        ),
    ]
